[package]
name = "dotenv"
version = "0.1.0"
authors = ["wangzhf <zhifengtech@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
# dotenv_macros = "0.10.0"
